// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package xdp

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type xdpDipVxlanValue struct {
	IfaceIndex [8]uint32
	VxlanIP    [8]uint32
	LbFactor   uint16
	_          [2]byte
}

type xdpIfaceMac struct {
	Ipaddr uint32
	Mac    [6]uint8
	_      [2]byte
}

type xdpIpDstKey struct{ Da uint32 }

type xdpIpDstValue struct {
	Da         uint32
	IfaceIndex uint32
	Mac        [6]uint8
	_          [2]byte
}

type xdpVxlanHeader struct{ Header [50]uint8 }

// loadXdp returns the embedded CollectionSpec for xdp.
func loadXdp() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_XdpBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load xdp: %w", err)
	}

	return spec, err
}

// loadXdpObjects loads xdp and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*xdpObjects
//	*xdpPrograms
//	*xdpMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadXdpObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadXdp()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// xdpSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpSpecs struct {
	xdpProgramSpecs
	xdpMapSpecs
	xdpVariableSpecs
}

// xdpProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpProgramSpecs struct {
	XdpRedirectGateway    *ebpf.ProgramSpec `ebpf:"xdp_redirect_gateway"`
	XdpStripVxlanRedirect *ebpf.ProgramSpec `ebpf:"xdp_strip_vxlan_redirect"`
}

// xdpMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpMapSpecs struct {
	DipVxlan       *ebpf.MapSpec `ebpf:"dipVxlan"`
	Gateway        *ebpf.MapSpec `ebpf:"gateway"`
	IfaceMacMap    *ebpf.MapSpec `ebpf:"ifaceMacMap"`
	Ip2Iface       *ebpf.MapSpec `ebpf:"ip2Iface"`
	VxlanHeaderMap *ebpf.MapSpec `ebpf:"vxlanHeaderMap"`
	VxlanIface     *ebpf.MapSpec `ebpf:"vxlanIface"`
}

// xdpVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type xdpVariableSpecs struct {
}

// xdpObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadXdpObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpObjects struct {
	xdpPrograms
	xdpMaps
	xdpVariables
}

func (o *xdpObjects) Close() error {
	return _XdpClose(
		&o.xdpPrograms,
		&o.xdpMaps,
	)
}

// xdpMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadXdpObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpMaps struct {
	DipVxlan       *ebpf.Map `ebpf:"dipVxlan"`
	Gateway        *ebpf.Map `ebpf:"gateway"`
	IfaceMacMap    *ebpf.Map `ebpf:"ifaceMacMap"`
	Ip2Iface       *ebpf.Map `ebpf:"ip2Iface"`
	VxlanHeaderMap *ebpf.Map `ebpf:"vxlanHeaderMap"`
	VxlanIface     *ebpf.Map `ebpf:"vxlanIface"`
}

func (m *xdpMaps) Close() error {
	return _XdpClose(
		m.DipVxlan,
		m.Gateway,
		m.IfaceMacMap,
		m.Ip2Iface,
		m.VxlanHeaderMap,
		m.VxlanIface,
	)
}

// xdpVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadXdpObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpVariables struct {
}

// xdpPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadXdpObjects or ebpf.CollectionSpec.LoadAndAssign.
type xdpPrograms struct {
	XdpRedirectGateway    *ebpf.Program `ebpf:"xdp_redirect_gateway"`
	XdpStripVxlanRedirect *ebpf.Program `ebpf:"xdp_strip_vxlan_redirect"`
}

func (p *xdpPrograms) Close() error {
	return _XdpClose(
		p.XdpRedirectGateway,
		p.XdpStripVxlanRedirect,
	)
}

func _XdpClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed xdp_x86_bpfel.o
var _XdpBytes []byte
